# Generated by Django 2.2.1 on 2019-05-07 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('project_phase', models.CharField(choices=[('1', 'Image Downloading'), ('2', 'ImageNet Classification'), ('6', 'Merger'), ('4', 'Price Comparison'), ('3', 'Color Classification'), ('7', 'Completion'), ('5', 'Text Comparison')], max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
            options={
                'verbose_name_plural': 'ProjectStatus',
            },
        ),
    ]
