# Generated by Django 2.2.1 on 2019-05-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190507_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='asynctask_id',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='project_phase',
            field=models.CharField(choices=[('4', 'Price Comparison'), ('2', 'ImageNet Classification'), ('6', 'Merger'), ('1', 'Image Downloading'), ('7', 'Completion'), ('3', 'Color Classification'), ('5', 'Text Comparison')], max_length=20),
        ),
    ]
