# Generated by Django 2.2.1 on 2019-05-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20190507_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='file_location',
            new_name='file_name',
        ),
        migrations.AlterField(
            model_name='project',
            name='total_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='total_unique_products',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='project_phase',
            field=models.CharField(choices=[('6', 'Merger'), ('5', 'Text Comparison'), ('7', 'Completion'), ('1', 'Image Downloading'), ('4', 'Price Comparison'), ('3', 'Color Classification'), ('2', 'ImageNet Classification')], max_length=20),
        ),
    ]
