# Generated by Django 2.2.1 on 2019-05-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('file_location', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('Completed', 'Completed'), ('Failed', 'Failed')], max_length=20)),
                ('failed_log', models.CharField(blank=True, max_length=500, null=True)),
                ('total_records', models.IntegerField()),
                ('total_unique_products', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
