# Generated by Django 2.2.1 on 2019-05-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='project_completion_percentage',
            field=models.CharField(default='0.0%', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='project_phase',
            field=models.CharField(choices=[('5', 'Text Comparison'), ('6', 'Merger'), ('4', 'Price Comparison'), ('2', 'ImageNet Classification'), ('3', 'Color Classification'), ('7', 'Completion'), ('1', 'Image Downloading')], max_length=20),
        ),
    ]
