# Generated by Django 2.2.1 on 2019-05-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190507_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Terminated', 'Terminated')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='project_phase',
            field=models.CharField(choices=[('1', 'Image Downloading'), ('6', 'Merger'), ('2', 'ImageNet Classification'), ('7', 'Completion'), ('3', 'Color Classification'), ('4', 'Price Comparison'), ('5', 'Text Comparison')], max_length=20),
        ),
    ]
