# Generated by Django 2.2.1 on 2019-05-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20190508_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Terminated', 'Terminated'), ('H_InProgress', 'H_InProgress'), ('H_Completed', 'H_Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectstatus',
            name='project_phase',
            field=models.CharField(choices=[('6', 'Merger'), ('1', 'Image Downloading'), ('2', 'ImageNet Classification'), ('5', 'Text Comparison'), ('4', 'Price Comparison'), ('7', 'Completion'), ('3', 'Color Classification')], max_length=20),
        ),
    ]
