CONFIDENCE_MATRIX_MAPPING_TYPE={
	"testrest":{
		"properties":{
		"s_vs_r_image_match":{
			"type":"float"	
		},
		"title_match":{
			"type":"float"	
		},
		"price_diff_per_sys":{
			"type":"float"	
		},
		"confidence_score":{
			"type":"float"
		},
				"mpn_match":{
			"type":"integer"
		},
			"gtin_match":{
			"type":"integer"
		},
			"asin_match":{
			"type":"integer"
		},
			"upc_match":{
			"type":"integer"
		}
		}
	}
}